it("creates a to-do", function () {
    cy.visit("/")
    // cy.findByPlaceholderText("Enter a To-Do")
    //     .type("Add our 1st to-do")
    // cy.findByRole("button", { name: "Add To-Do" }).click()
    cy.addTodo("Add our 1st to-do")
    cy.findByText("Add our 1st to-do").should("exist")
})

it("completes a to-do", function () {
    cy.visit("/")
    cy.addTodo("Complete this to-do")
    cy.toggleTodoCompleted("Complete this to-do")
    cy.findByTestId("completed-todos")
        .should("contain", "Complete this to-do")
    cy.findByTestId("incomplete-todos")
        .should("not.contain", "Complete this to-do")
})

it("deletes a to-do", function () {
    cy.visit("/")
    cy.addTodo("Delete this to-do")
    cy.toggleTodoCompleted("Delete this to-do")
    cy.archiveCompletedTodo("Delete this to-do")
    cy.findByRole("link", { name: "Archive" }).click()
    cy.deleteArchivedTodo("Delete this to-do")
    cy.document().its("body")
        .should("not.contain", "Delete this to-do")
    cy.findByRole("link", { name: "Home" }).click()
    cy.document().its("body")
        .should("not.contain", "Delete this to-do")
})
